### ISSUE TITLE
`[EPIC]` Make Conan the ONLY program that needs to be installed

### ISSUE THREAD

**Issue by kammce** [libhal-google/.github#52]
All other tools can be installed via conan tool packages. But these packages do not wide spread support beyond Linux.  A list of the necessary 

- [x] CMake (already well supported by conan)
- [x] ArmGnuToolchain (already supported here: https://github.com/libhal/arm-gnu-toolchain)
- [ ] Make 
- [ ] GCC (desire is to use this for default profiles)
- [ ] clang-tidy
